services:
  web:
    container_name: flask
    build: .
    ports:
      - "8000:5000"
    environment:
      FLASK_DEBUG: "true"
    restart: on-failure
    depends_on:
      - mysql
      - memcached
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "33060:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
        - "11211:11211"
volumes:
  mysql-data: