services:
  tarantool:
    build: tarantool/src
    ports:
      - "3302:3302"
  web:
    container_name: flask
    build: .
    ports:
      - "8000:8000"
    environment:
      FLASK_DEBUG: "true"
    restart: on-failure
    depends_on:
      - tarantool
      - memcached
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
        - "11211:11211"
volumes:
  mysql-data: